name: Suzuki

channels:
  - conda-forge

dependencies:
  # conda-core
  - python=3.10
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - pip
  # conda-spec
  - nd2
  - napari
  - pyqt
  - spyder
  # conda_tf-gpu
  - cudatoolkit=11.2
  - cudnn=8.1
  - pip:
    # pip-core
    - bd-tools
    # pip-spec
    # pip_tf-gpu
    - albumentations
    - segmentation-models
    - tensorflow-gpu==2.10